stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t resume-cupid .
  only:
    - main

test:
  stage: test
  script:
    - docker run resume-cupid pytest
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker push resume-cupid
  only:
    - main