api {
    web_server: https://app.clear.ml
    api_server: https://api.clear.ml
    files_server: https://files.clear.ml
    credentials {
        "default" {
            access_key: "8M6RWE24K3BBJM3EX3DNA4ST9YTJ6W"
            secret_key: "r1UhDK351zsTzY6vHV148WJN265iWQRJOrq8PdrcW4HJNkE0xbBYRk0dN8YQdOlLkcY"
        }
    }
}
