services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["streamlit", "run", "resume_calibrator.py"]
    deploy:
      resources:
        limits:
          memory: 1.5g
        reservations:
          memory: 1g
