version: '3.8'

services:
  app:
    image: your_image_name
    container_name: resume_calibrator_app
    volumes:
      - /home/rezcupid2024/Resume_Cupid_CrewAI_HF_Llama3/model_new:/app/model_new
    ports:
      - "8501:8501"
